<?php

namespace Phunk;

use PHPUnit_Framework_TestCase;

/**
 * Test class for Util.
 * Generated by PHPUnit on 2011-10-23 at 17:55:58.
 */

class UtilTest extends PHPUnit_Framework_TestCase
{
    /**
     * @test
     */
    public function testTune_up()
    {
        $expected = $app = function($env)
        {
        };

        Util::tune_up($app, array());
        assertSame($expected, $app);

        Util::tune_up($app, array('\\Phunk\\Test\\Collaborator\\Mock'));
        assertNotSame($expected, $app);
        assertSame($expected, \Phunk\Test\Collaborator\Mock::$_app);
        assertSame(array(), \Phunk\Test\Collaborator\Mock::$_options);

        $app = $expected;
        $options = array(1, 2, 3, 4, 5);
        Util::tune_up($app, array('\\Phunk\\Test\\Collaborator\\Mock' => $options));
        assertNotSame($expected, $app);
        assertSame($expected, \Phunk\Test\Collaborator\Mock::$_app);
        assertSame($options, \Phunk\Test\Collaborator\Mock::$_options);
    }

    /**
     * @test
     */
    public function testLoad_phunki()
    {
        /* @var $app Closure */
        $app = Util::load_phunki(__DIR__ . '/UtilTest/test_phunki_1.php');
        assertTrue(is_callable($app));
        assertSame(array(200, array(), 'test1'), $app(array()));

        $app = Util::load_phunki(__DIR__ . '/UtilTest/test_phunki_2.php');
        assertTrue(is_callable($app));
        assertSame(array(200, array(), 'test2'), $app(array()));
    }

    /**
     * @test
     */
    public function testPhunk_up()
    {
        ob_start();
        Util::phunk_up(__DIR__ . '/UtilTest/test_phunki_1.php', array('handler' => 'Beat'));
        $output = ob_get_clean();
        $expected = "HTTP/1.1 200 OK\r\n\r\n" . "test1";
        assertSame($expected, $output);
    }

    /**
     * @test
     */
    public function test_fix_class_name()
    {
        \assertSame('Phunk\\Collaborator\\Foo', Util::_fix_class_name('Foo', 'Phunk\\Collaborator'));
        \assertSame('Phunk\\Collaborator\\Foo', Util::_fix_class_name('Phunk\\Collaborator\\Foo', 'Phunk\\Collaborator'));
        \assertSame('\\Foo', Util::_fix_class_name('\\Foo', 'Phunk\\Collaborator'));
    }
}

namespace Phunk\Test\Collaborator;

class Mock implements \Phunk\Collaborator
{
    static $_app;
    static $_options;

    /**
     * @static
     * @param callable $app
     * @param array $options
     * @return callable
     */
    static function collaborate(callable $app, array $options = array())
    {
        self::$_app = $app;
        self::$_options = $options;

        return function($env) use ($app)
        {
            return $app($env);
        };
    }
}
